// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_9HEqMuPgm-TsHSwJD6Z4Zo3sY5AK3vc',
    appId: '1:583598744130:web:5d7b7c99a59140acfe03db',
    messagingSenderId: '583598744130',
    projectId: 'hambrout',
    authDomain: 'hambrout.firebaseapp.com',
    storageBucket: 'hambrout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmontLNrLIwq2SuHUU_WhlHnEX969AF-I',
    appId: '1:583598744130:android:24c93f608a6ceba0fe03db',
    messagingSenderId: '583598744130',
    projectId: 'hambrout',
    storageBucket: 'hambrout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTCJgA8yfSUfJGF03B5UzWpU0yaNZQ50',
    appId: '1:583598744130:ios:efc90167eaa7e1c7fe03db',
    messagingSenderId: '583598744130',
    projectId: 'hambrout',
    storageBucket: 'hambrout.appspot.com',
    iosClientId: '583598744130-ghse0ftppnma6b41kf5nvu5tn89s96kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hambrout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTCJgA8yfSUfJGF03B5UzWpU0yaNZQ50',
    appId: '1:583598744130:ios:efc90167eaa7e1c7fe03db',
    messagingSenderId: '583598744130',
    projectId: 'hambrout',
    storageBucket: 'hambrout.appspot.com',
    iosClientId: '583598744130-ghse0ftppnma6b41kf5nvu5tn89s96kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hambrout',
  );
}
